/*
 * This source file was generated by the Gradle 'init' task
 */
package hello_server;

import org.junit.jupiter.api.Test;
import hello_server.App;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(true, "app should have a greeting");
    }
}
